name: Unit Testing with Jest

on:
  push:
    branches:
      - main
      - feat/server-merge

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: |
          cd client
          npm install
          npm run build -- if-present
          npm test