name: Unit Tests and SonarCloud Analysis

on:
  push:
    branches:
      - main
      - feat/server-merge

jobs:
  buildAndTest:
    name: Unit Testing in Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: |
          cd client
          npm install
          npm run build -- if-present
          npm test

          
  sonarCloudTrigger:
        needs: buildAndTest
        name: SonarCloud Trigger
        runs-on: ubuntu-latest
        steps:
          - name: Clone Repo
            uses: actions/checkout@v2
          - name: Analyse with SonarCloud
            uses: sonarsource/sonarcloud-github-action@v1.3
            env:
              GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}